
surface.CreateFont(
"HUDFloatOne",
{
	font = "halflife2",
	extended = false,
	size = 36,
	weight = 2000,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont(
"HUDClock1",
{
	font 		= "ChatFont",
	extended 	= false,
	size 		= 42,
	weight 		= 600,
	blursize 	= 1,
	scanlines 	= 2,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= true,
	outline 	= false
}
)
surface.CreateFont(
"HUDClock2",
{
	font 		= "ChatFont",
	extended 	= false,
	size 		= 42,
	weight 		= 600,
	blursize 	= 4,
	scanlines 	= 0,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= false,
	outline 	= false
}
)
surface.CreateFont(
"HUDFont1",
{
	font 		= "couriernew",
	extended 	= false,
	size 		= 32,
	weight 		= 500,
	blursize 	= 0,
	scanlines 	= 0,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= false,
	outline 	= false
}
)
surface.CreateFont(
"HUDFont2",
{
	font 		= "Arial",
	extended 	= false,
	size 		= 12,
	weight 		= 100,
	blursize 	= 0,
	scanlines 	= 0,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= false,
	outline 	= false
}
)
surface.CreateFont(
"HUDWeapon",
{
	font 		= "halflife2",
	extended 	= false,
	size 		= 12,
	weight 		= 100,
	blursize 	= 0,
	scanlines 	= 0,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= false,
	outline 	= false
}
)
surface.CreateFont(
"HUDAmmo1",
{
	font 		= "Arial",
	extended 	= false,
	size 		= 48,
	weight 		= 100,
	blursize 	= 0,
	scanlines 	= 0,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= false,
	outline 	= false
}
)
surface.CreateFont(
"HUDAmmo2",
{
	font 		= "Arial",
	extended 	= false,
	size 		= 32,
	weight 		= 100,
	blursize 	= 0,
	scanlines 	= 0,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= false,
	outline 	= false
}
)
surface.CreateFont(
"HUDScore1",
{
	font 		= "Arial",
	extended 	= false,
	size 		= 32,
	weight 		= 100,
	blursize 	= 4,
	scanlines 	= 2,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= true,
	outline 	= false
}
)
surface.CreateFont(
"HUDScore2",
{
	font 		= "Arial",
	extended 	= false,
	size 		= 32,
	weight 		= 100,
	blursize 	= 1,
	scanlines 	= 0,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= false,
	outline 	= false
}
)
surface.CreateFont(
"HUDScore3",
{
	font 		= "Arial",
	extended 	= false,
	size 		= 24,
	weight 		= 200,
	blursize 	= 1,
	scanlines 	= 0,
	antialias 	= true,
	underline 	= false,
	italic 		= false,
	strikeout 	= false,
	symbol 		= false,
	rotary 		= false,
	shadow 		= false,
	additive 	= false,
	outline 	= false
}
)

surface.CreateFont( "HUDBack", {
	font = "halflife2", 
	extended = false,
	size = 64,
	weight = 2000,
	blursize = 10,
	scanlines = 2,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = true,
	outline = true,
} )

surface.CreateFont( "HUDBkg", {
	font = "halflife2", 
	extended = false,
	size = 64,
	weight = 2000,
	blursize = 2,
	scanlines = 1,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "HUDFront", {
	font = "halflife2",
	extended = false,
	size = 48,
	weight = 2000,
	blursize = 6,
	scanlines = 4,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = true,
	outline = false,
} )

surface.CreateFont( "HUDMain", {
	font = "halflife2",
	extended = false,
	size = 48,
	weight = 500,
	blursize = 1,
	scanlines = 2,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "ScoreBack", {
	font = "Arial",
	extended = false,
	size = 48,
	weight = 2000,
	blursize = 6,
	scanlines = 1,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )
surface.CreateFont( "ScoreMain", {
	font = "Arial",
	extended = false,
	size = 48,
	weight = 2000,
	blursize = 2,
	scanlines = 2,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "HUDSmallBack", {
	font = "Arial",
	extended = false,
	size = 32,
	weight = 2000,
	blursize = 6,
	scanlines = 2,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "HUDSmall", {
	font = "Arial",
	extended = false,
	size = 32,
	weight = 500,
	blursize = 1,
	scanlines = 2,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "ScoreSmall", {
	font = "Arial",
	extended = false,
	size = 12,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "ScoreBasicBack", {
	font = "Arial",
	extended = false,
	size = 24,
	weight = 500,
	blursize = 3,
	scanlines = 2,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = true,
	outline = false,
} )
surface.CreateFont( "ScoreBasic", {
	font = "Arial",
	extended = false,
	size = 24,
	weight = 500,
	blursize = 0,
	scanlines = 1,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )
surface.CreateFont( "HUDFloatOne", {
	font = "halflife2",
	extended = false,
	size = 36,
	weight = 2000,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )
surface.CreateFont( "HUDFloatTwo", {
	font = "Trebuchet18",
	extended = false,
	size = 12,
	weight = 2000,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "MENUBkg", {
	font = "Trebuchet18",
	extended = false,
	size = 48,
	weight = 2000,
	blursize = 7,
	scanlines = 2,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = true,
	outline = false,
} )
surface.CreateFont( "ClassDesc", {
	font = "Arial",
	extended = false,
	size = 16,
	weight = 500,
	blursize = 0,
	scanlines = 1,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )